source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'hirb'
gem 'kaminari'
gem 'puma'
gem 'rails_12factor'
gem 'figaro'
gem 'devise'
gem 'paperclip', '~> 4.2'
gem 'aws-sdk', '< 2.0'
gem 'simple_form'
group :test, :development do
  gem 'faker'
  gem 'quiet_assets'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'simplecov'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem "awesome_print", require: "ap"
  gem 'spring'
end
